CREATE TABLE IF NOT EXISTS email_auth (
    id BIGSERIAL PRIMARY KEY,
    email TEXT NOT NULL UNIQUE,
    password TEXT NOT NULL,
    name TEXT,
    username TEXT UNIQUE,
    phone TEXT UNIQUE,
    phone_verified_at TIMESTAMPTZ,
    verified BOOLEAN NOT NULL DEFAULT FALSE,
    avatar TEXT,
    banner TEXT,
    bio TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS sessions (id BIGSERIAL PRIMARY KEY, user_id BIGINT NOT NULL REFERENCES email_auth(id) ON DELETE CASCADE, token_hash TEXT NOT NULL UNIQUE, expires_at TIMESTAMPTZ NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, revoked_at TIMESTAMPTZ);
CREATE TABLE IF NOT EXISTS verification_codes (id BIGSERIAL PRIMARY KEY, subject TEXT NOT NULL, purpose TEXT NOT NULL CHECK (purpose IN ('email','phone')), code_hash TEXT NOT NULL, expires_at TIMESTAMPTZ NOT NULL, attempts INTEGER NOT NULL DEFAULT 0, last_sent_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, consumed_at TIMESTAMPTZ, UNIQUE(subject,purpose));
CREATE TABLE IF NOT EXISTS password_resets (id BIGSERIAL PRIMARY KEY, user_id BIGINT NOT NULL REFERENCES email_auth(id) ON DELETE CASCADE, token_hash TEXT NOT NULL UNIQUE, expires_at TIMESTAMPTZ NOT NULL, consumed_at TIMESTAMPTZ, created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS posts (id BIGSERIAL PRIMARY KEY, user_id BIGINT NOT NULL REFERENCES email_auth(id) ON DELETE CASCADE, content TEXT NOT NULL CHECK (length(content) BETWEEN 1 AND 5000), image_path TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS follows (follower_id BIGINT NOT NULL REFERENCES email_auth(id) ON DELETE CASCADE, following_id BIGINT NOT NULL REFERENCES email_auth(id) ON DELETE CASCADE, created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY(follower_id,following_id), CHECK(follower_id<>following_id));
CREATE TABLE IF NOT EXISTS post_likes (user_id BIGINT NOT NULL REFERENCES email_auth(id) ON DELETE CASCADE, post_id BIGINT NOT NULL REFERENCES posts(id) ON DELETE CASCADE, created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY(user_id,post_id));
CREATE TABLE IF NOT EXISTS comments (id BIGSERIAL PRIMARY KEY, user_id BIGINT NOT NULL REFERENCES email_auth(id) ON DELETE CASCADE, post_id BIGINT NOT NULL REFERENCES posts(id) ON DELETE CASCADE, content TEXT NOT NULL CHECK (length(content) BETWEEN 1 AND 1000), created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS conversations (id BIGSERIAL PRIMARY KEY, created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS conversation_participants (conversation_id BIGINT NOT NULL REFERENCES conversations(id) ON DELETE CASCADE, user_id BIGINT NOT NULL REFERENCES email_auth(id) ON DELETE CASCADE, joined_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY(conversation_id,user_id));
CREATE TABLE IF NOT EXISTS messages (id BIGSERIAL PRIMARY KEY, conversation_id BIGINT NOT NULL REFERENCES conversations(id) ON DELETE CASCADE, sender_id BIGINT NOT NULL REFERENCES email_auth(id) ON DELETE CASCADE, content TEXT NOT NULL CHECK(length(content) BETWEEN 1 AND 4000), created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, edited_at TIMESTAMPTZ);
CREATE TABLE IF NOT EXISTS notifications (id BIGSERIAL PRIMARY KEY, user_id BIGINT NOT NULL REFERENCES email_auth(id) ON DELETE CASCADE, actor_id BIGINT REFERENCES email_auth(id) ON DELETE CASCADE, kind TEXT NOT NULL, entity_id BIGINT, read_at TIMESTAMPTZ, created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX IF NOT EXISTS idx_sessions_user_active ON sessions(user_id,expires_at);
CREATE INDEX IF NOT EXISTS idx_posts_feed ON posts(created_at DESC,id DESC);
CREATE INDEX IF NOT EXISTS idx_posts_author ON posts(user_id,created_at DESC);
CREATE INDEX IF NOT EXISTS idx_comments_post ON comments(post_id,created_at);
CREATE INDEX IF NOT EXISTS idx_likes_post ON post_likes(post_id);
CREATE INDEX IF NOT EXISTS idx_follows_following ON follows(following_id);
CREATE INDEX IF NOT EXISTS idx_participants_user ON conversation_participants(user_id,conversation_id);
CREATE INDEX IF NOT EXISTS idx_messages_conversation ON messages(conversation_id,created_at,id);
CREATE INDEX IF NOT EXISTS idx_notifications_user ON notifications(user_id,created_at DESC);
